server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip básico
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml application/xml;
    gzip_min_length 1024;

    # Cache para estáticos (ajusta tiempos si quieres)
    location ~* \.(?:js|css|png|jpg|jpeg|gif|svg|ico|webp)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    # PDFs sin cache agresivo (para poder cambiarlos fácil)
    location ~* \.pdf$ {
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
    }

    # Servir archivos tal cual
    location / {
        try_files $uri $uri/ =404;
    }
}
